[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {workspace = true}
tokio-tungstenite = {workspace = true}
serde = {workspace = true}
serde_millis = {workspace = true}
futures-util = {workspace = true}
